package com.sample

import com.sample.DroolsTest.Wyswietlanie;
import com.sample.DroolsTest.FormatOdp;
import com.sample.DroolsTest.Pytanie;
import com.sample.DroolsTest.Cecha;
import java.util.List;
import java.util.ArrayList;
 
query "Wyswielt"
    w : Wyswietlanie();
end

// ************************************
//			PYTANIA
//		10 pytañ g³ownych, 11 szczegó³oweych i 6 ogolnych
// ************************************


// pytania wynikaj¹ce z innych maj¹ wy¿szy prioritet, aby zaraz potem siê zada³y
rule "Wielkosc" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wielkosc");
    then
    	insert(new Pytanie("Wielkosc"));
        w.set("Czy wielkoœæ twojej postaci ma znaczenie?", "Wielkoœæ", FormatOdp.YESNO);
    	retract(w);
end

rule "WielkoscDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Wielkosc");
    	not Pytanie(tekst == "WielkoscDwa");
    then
    	insert(new Pytanie("WielkoscDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Ma³a");
    		opcje.add("Du¿a");
    		opcje.add("Wielka");
        w.set("Jak du¿¹ postaci¹ wolisz?", "Wielkosc", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end


rule "Wiek" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wiek");
    then
    	insert(new Pytanie("Wiek"));
        w.set("Czy wiek towjej postaci ma znaczenie?", "Wiek", FormatOdp.YESNO);
    	retract(w);
end


rule "WiekDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Wielkosc");
    	not Pytanie(tekst == "WielkoscDwa");
    then
    	insert(new Pytanie("WielkoscDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("M³oda");
    		opcje.add("W œrednim wieku");
    		opcje.add("Stara");
        w.set("Jaki wiek twojej postac preferujesz?", "Wiek", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Walczy" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Walczy");
    then
    	insert(new Pytanie("Walczy"));
        w.set("Czy chcesz walczyæ?", "Walczy", FormatOdp.YESNO);
    	retract(w);
end

rule "Bron" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Walczy");
    	not Pytanie(tekst == "Bron");
    then
    	insert(new Pytanie("Bron"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Miecz");
    		opcje.add("Kostur");
    		opcje.add("Topór");
    		opcje.add("£uk");
    		opcje.add("Kusza");
    		opcje.add("Pistolet");
    		opcje.add("Sztylety");
    		opcje.add("Maczuga");
        w.set("Jakie bronie lubisz?", "Bron",  FormatOdp.WIELOKROTYN, opcje);
    	retract(w);
end

rule "Wszechstronny" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wszechstronny");
    then
    	insert(new Pytanie("Wszechstronny"));
        w.set("Czy chcesz byæ wszechstronny(ale nie wybitny w konkretnej dziedzinie)?", "Wszechstronny", FormatOdp.YESNO);
    	retract(w);
end

rule "WszechstronnyDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha( tresc == "Wszechstronny");
    	not Pytanie(tekst == "WszechstronnyDwa");
    then
    	insert(new Pytanie("WszechstronnyDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Inteligencja");
    		opcje.add("Spryt");
    		opcje.add("Si³a");
        w.set("Jaka cecha jest dla Ciebie najwa¿niejsza?", "Wszechtronny", FormatOdp.YESNO);
    	retract(w);
end



rule "Zaklecia" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Zaklecia");
    then
    	insert(new Pytanie("Zaklecia"));
        w.set("Czy chcesz uzywac zaklec?", "Zaklecia", FormatOdp.YESNO);
    	retract(w);
end


rule "ZakleciaDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Zaklecia");
    	not Pytanie(tekst == "ZakleciaDwa");
    then
    	insert(new Pytanie("ZakleciaDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Lecznicze");
    		opcje.add("Wojenne");
    		opcje.add("Kl¹twy");
    		opcje.add("Wspieraj¹ce");
        w.set("Jakie zaklêcia wolisz?", "Zaklecia", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end


rule "Kolor" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Kolor");
    then
    	insert(new Pytanie("Kolor"));
        w.set("Czy masz ulubiony kolor?", "Kolor", FormatOdp.YESNO);
    	retract(w);
end

rule "KolorDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Kolor");
    	not Pytanie(tekst == "KolorDwa");
    then
    	insert(new Pytanie("KolorDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Ró¿owy");
    		opcje.add("Zielony");
    		opcje.add("Czarny");
    		opcje.add("Bia³y");
    		opcje.add("Czerwony");
    		opcje.add("Inny");
        w.set("Jaki jest twój ulubiony kolor?", "Kolor", FormatOdp.RADIOBUTTON, opcje);
        retract(w);
end

rule "Siedziba" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Siedziba");
    then
    	insert(new Pytanie("Siedziba"));
        w.set("Czy chcesz miec sta³¹ siedzibê?", "Siedziba", FormatOdp.YESNO);
    	retract(w);
end

rule "SiedzibaDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Siedziba");
    	not Pytanie(tekst == "SiedzibaDwa");
    then
    	insert(new Pytanie("SiedzibaDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("W chacie");
    		opcje.add("W lesie");
    		opcje.add("W grocie");
    		opcje.add("W wie¿y");
        w.set("Gdzie chcia³byœ zamieszkaæ?", "SiedzibaDwa", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Pancerz" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Pancerz");
    then
    	insert(new Pytanie("Pancerz"));
        w.set("Czy chcesz byc opancerzony?", "Pancerz", FormatOdp.YESNO);
    	retract(w);
end

rule "PancerzDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Pancerz");
    	not Pytanie(tekst == "PancerzDwa");
    then
    	insert(new Pytanie("PancerzDwa"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Ciê¿k¹ zbrojê");
    		opcje.add("He³m z rogami");
    		opcje.add("Tarczê");
    		opcje.add("Lekk¹ zbrojê");
    		opcje.add("Skórzan¹ zbrojê");
    		
        w.set("Jakie opancerzenie chcia³byœ nosiæ?", "Pancerz", FormatOdp.WIELOKROTYN, opcje);
    	retract(w);
end

rule "Wegetarianin" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wegetarianin");
    then
    	insert(new Pytanie("Wegetarianin"));
        w.set("Czy jesteœ wegetarianinem?", "Wegetarianin", FormatOdp.YESNO);
    	retract(w);
end

rule "Mieso" salience 2
    when
    	w : Wyswietlanie();
    	not Cecha (tresc == "Wegetarianin");
    	Pytanie(tekst == "Wegetarianin");
    	not Pytanie(tekst == "Mieso");
    then
    	insert(new Pytanie("Mieso"));
        w.set("Czy zjad³byœ miêso cz³onka w³asnej rasy?", "Mieso", FormatOdp.YESNO);
    	retract(w);
end

rule "Zwierze" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Zwierze");
    then
    	insert(new Pytanie("Zwierze"));
        w.set("Czy lubisz zwierzêta?", "Zwierze", FormatOdp.YESNO);
    	retract(w);
end
 
rule "ZwierzDwa" salience 2
    when
    	w : Wyswietlanie();
    	Cecha (tresc == "Zwierze");
    	not Pytanie(tekst == "ZwierzeDwa");
    then
    	insert(new Pytanie("ZwierzeDwa"));
        w.set("Czy chcia³byœ mieæ zwierzê?", "ZwierzeDwa", FormatOdp.YESNO);
    	retract(w);
end


rule "ZwierzeTrzy" salience 3
    when
    	w : Wyswietlanie();
    	Cecha( tresc == "ZwierzeDwa");
    	not Pytanie(tekst == "ZwierzeTrzy");
    then
    	insert(new Pytanie("ZwierzeTrzy"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Konia");
    		opcje.add("Wilka");
    		opcje.add("Kruka");
    		opcje.add("Sowê");
        w.set("Jakie zwierzê chcia³byœ mieæ?", "Piora",  FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end


rule "Uczciwy" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Uczciwy");
    then
    	insert(new Pytanie("Uczciwy"));
        w.set("Czy znasz pojêcie uczciwoœci?", "Uczciwy", FormatOdp.YESNO);
    	retract(w);
end

rule "Piekny" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Piekny");
    then
    	insert(new Pytanie("Piekny"));
        w.set("Czy chcesz byæ piêkny?", "Piekny", FormatOdp.YESNO);
    	retract(w);
end

rule "Hobby" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Hobby");
    then
    	insert(new Pytanie("Hobby"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Ksiêgi");
    		opcje.add("Zabawa");
    		opcje.add("Mechanizmy");
    		opcje.add("Zielarstwo");
    		opcje.add("numizmatyka");
    		opcje.add("zbieranie kamieni");
    		opcje.add("zbieranie wszystkiego");
        w.set("Jakie jest Twoje hobby?", "Hobby",  FormatOdp.WIELOKROTYN, opcje);
    	retract(w);
end

rule "Dobry" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Dobro");
    then
    	insert(new Pytanie("Dobro"));
        w.set("Czy chcesz czyniæ dobro?", "Dobry", FormatOdp.YESNO);
    	retract(w);
end

rule "Szybki" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Szybki");
    then
    	insert(new Pytanie("Szybki"));
        w.set("Czy lubisz prêdkoœæ?", "Szybki", FormatOdp.YESNO);
    	retract(w);
end

rule "Wynalazki" salience 1
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wynalazki");
    then
    	insert(new Pytanie("Wynalazki"));
        w.set("Czy lubisz gad¿ety/wynalazki?", "Wynalazki", FormatOdp.YESNO);
    	retract(w);
end
// ************************************
//			 Rasy i Klasy 
//				20 klas
// ************************************

//Ludzie
rule "Mag" salience 3
    when
    	w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Mag", true);        
    	retract(w);
end

rule "Wojownik" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Wojownik", true);        
    	retract(w);
end

rule "Paladyn" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
	then
	w.set("Paladyn", true);        
    	retract(w)
end


rule "£otrzyk" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("£otrzyk", true);        
    	retract(w);
end

rule "Strzelec" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Strzelec", true);        
    	retract(w);
end

rule "In¿yniert" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("In¿ynier", true);        
    	retract(w);
end

//Orki
rule "Barbarzynca" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Barbarzynca", true);        
    	retract(w);
end


rule "Szaman" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Szaman", true);        
    	retract(w);
end

rule "Lowca" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Lowca", true);        
    	retract(w);
end

rule "Jezdziec Wilkow" salience 3
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Nidoking", true);        
    	retract(w);
end

rule "Olbrzym" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Olbrzym", true);        
    	retract(w);
end

rule "Gremlin" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Gremlin", true);        
    	retract(w);
end

//Elfy
rule "Uzdrowicie;" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Uzdrowiciel", true);        
    	retract(w);
end

rule "Bard" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Bard", true);        
    	retract(w);
end

rule "£ucznik" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("£ucznik", true);        
    	retract(w);
end

rule "Assasyn" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Assasyn", true);        
    	retract(w);
end

rule "Druid" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Druid", true);        
    	retract(w);
end

rule "Mêdrzec" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Mêdrzec", true);        
    	retract(w);
end

//klasy bez rasy
rule "Dragonborn" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Dragonborn", true);        
    	retract(w);
end

rule "WiedŸmin" salience 3
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("WiedŸmin", true);        
    	retract(w);
end



/* Przyk³ad rule z odpowiedzi¹
rule "Arcanine"
	when
		w : Wyswietlanie();
		Cecha(tresc == "Nogi4");
		(or
			Cecha(tresc == "NogiKoloruPomaranczowego");
			Cecha(tresc == "NogiKoloruCzarnego");
		)
		Cecha(tresc == "Oczy2");
		Cecha(tresc == "Wzor");
		Cecha(tresc == "UszyKoloruPomaranczowego");
		Cecha(tresc == "OgonKoloruKremowego");
		Cecha(tresc == "Futro");
    then
    	w.set("Arcanine", true);        
    	retract(w);
end
*/