package com.sample

import com.sample.DroolsTest.Wyswietlanie;
import com.sample.DroolsTest.FormatOdp;
import com.sample.DroolsTest.Pytanie;
import com.sample.DroolsTest.Cecha;
import java.util.List;
import java.util.ArrayList;
 
query "Wyswielt"
    w : Wyswietlanie();
end

// ************************************
//			PYTANIA

rule "Nogi" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Nogi");
    then
    	insert(new Pytanie("Nogi"));
        w.set("Czy twoj pokemon ma nogi?", "Nogi", FormatOdp.YESNO);
    	retract(w);
end

rule "NogiLiczba" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Nogi");
    	not Pytanie(tekst == "NogiLiczba");
    then
    	insert(new Pytanie("NogiLiczba"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("1");
    		opcje.add("2");
    		opcje.add("3");
    		opcje.add("4");
    		opcje.add("5");
    		opcje.add("6");
        w.set("Ile nog ma twoj pokemon?", "Nogi", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "NogiKolor" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Nogi");
    	not Pytanie(tekst == "NogiKolor");
    then
    	insert(new Pytanie("NogiKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jaki jest kolor nog twojego pokemona?", "NogiKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end


rule "Oczy" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Oczy");
    then
    	insert(new Pytanie("Oczy"));
        w.set("Czy twoj pokemon ma oczy?", "Oczy", FormatOdp.YESNO);
    	retract(w);
end

rule "OczyLiczba" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Oczy");
    	not Pytanie(tekst == "OczyLiczba");
    then
    	insert(new Pytanie("OczyLiczba"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("1");
    		opcje.add("2");
    		opcje.add("3");
    		opcje.add("4");
        w.set("Ile oczu ma twoj pokemon?", "Oczy", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "OkreslicKolorOczu" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Oczy");
    	not Pytanie(tekst == "OkreslicKolorOczu");
    then
    	insert(new Pytanie("OkreslicKolorOczu"));
        w.set("Czy mozesz okreslic kolor oczu?", "OkreslicKolorOczu", FormatOdp.YESNO);
    	retract(w);
end

rule "OczyKolor" salience 2
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "OkreslicKolorOczu");
    	not Pytanie(tekst == "OczyKolor");
    then
    	insert(new Pytanie("OczyKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jaki jest kolor oczu ma twoj pokemona?", "OczyKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Wzor"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wzor");
    then
    	insert(new Pytanie("Wzor"));
        w.set("Czy twoj pokemon ma laty lub wzor?", "Wzor", FormatOdp.YESNO);
    	retract(w);
end

rule "Pazury"
    when
    	w : Wyswietlanie();
    	(or Cecha(tresc == "Rece");
    		Cecha(tresc == "Nogi");
    	)
    	not Pytanie(tekst == "Pazury");
    then
    	insert(new Pytanie("Pazury"));
        w.set("Czy twoj pokemon ma pazury?", "Pazury", FormatOdp.YESNO);
    	retract(w);
end

rule "Zeby"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Zeby");
    then
    	insert(new Pytanie("Zeby"));
        w.set("Czy twoj pokemon ma zeby?", "Zeby", FormatOdp.YESNO);
    	retract(w);
end

rule "Uszy" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Uszy");
    then
    	insert(new Pytanie("Uszy"));
        w.set("Czy twoj pokemon ma uszy?", "Uszy", FormatOdp.YESNO);
    	retract(w);
end

rule "UszyKolor" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Uszy");
    	not Pytanie(tekst == "UszyKolor");
    then
    	insert(new Pytanie("UszyKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jaki jest kolor uszu ma twoj pokemona?", "UszyKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Nosi"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Nosi");
    then
    	insert(new Pytanie("Nosi"));
        w.set("Czy twoj pokemon cos nosi?", "Nosi", FormatOdp.YESNO);
    	retract(w);
end

rule "Rogi" 
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Rogi");
    then
    	insert(new Pytanie("Rogi"));
        w.set("Czy twoj pokemon ma rogi?", "Rogi", FormatOdp.YESNO);
    	retract(w);
end

rule "RogiKolor"
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Rogi");
    	not Pytanie(tekst == "RogiKolor");
    then
    	insert(new Pytanie("RogiKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jakiego koloru sa rogi/czulki?", "RogiKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Ogon" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Ogon");
    then
    	insert(new Pytanie("Ogon"));
        w.set("Czy twoj pokemon ma ogon?", "Ogon", FormatOdp.YESNO);
    	retract(w);
end

rule "OgonKolor" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Ogon");
    	not Pytanie(tekst == "OgonKolor");
    then
    	insert(new Pytanie("OgonKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jakiego koloru jest ogon?", "OgonKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Skrzydla" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Skrzydla");
    then
    	insert(new Pytanie("Skrzydla"));
        w.set("Czy twoj pokemon ma skrzydla?", "Skrzydla", FormatOdp.YESNO);
    	retract(w);
end

rule "SkrzydlaKolor" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Skrzydla");
    	not Pytanie(tekst == "SkrzydlaKolor");
    then
    	insert(new Pytanie("SkrzydlaKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jakiego koloru sa skrzydla?", "SkrzydlaKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Rece" salience 2
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Rece");
    then
    	insert(new Pytanie("Rece"));
        w.set("Czy twoj pokemon ma rece?", "Rece", FormatOdp.YESNO);
    	retract(w);
end

rule "ReceKolor" salience 1
    when
    	w : Wyswietlanie();
    	Cecha(tresc == "Rece");
    	not Pytanie(tekst == "ReceKolor");
    then
    	insert(new Pytanie("ReceKolor"));
    	List<String> opcje = new ArrayList<String>();
    		opcje.add("Zielonego");
    		opcje.add("Pomaranczowego");
    		opcje.add("Kremowego");
    		opcje.add("Niebieskiego");
    		opcje.add("Blekitnego");
    		opcje.add("Czarnego");
    		opcje.add("Bialego");
    		opcje.add("Szarego");
    		opcje.add("Rozowego");
    		opcje.add("Brazowego");
    		opcje.add("Fioletowego");
    		opcje.add("Zoltego");
        w.set("Jakiego koloru sa rece?", "ReceKoloru", FormatOdp.RADIOBUTTON, opcje);
    	retract(w);
end

rule "Bron"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Bron");
    then
    	insert(new Pytanie("Bron"));
        w.set("Czy twoj pokemon ma bron?", "Bron", FormatOdp.YESNO);
    	retract(w);
end

rule "Dziob"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Dziob");
    then
    	insert(new Pytanie("Dziob"));
        w.set("Czy twoj pokemon ma dziob?", "Dziob", FormatOdp.YESNO);
    	retract(w);
end

rule "Piora"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Piora");
    then
    	insert(new Pytanie("Piora"));
        w.set("Czy twoj pokemon ma piora?", "Piora", FormatOdp.YESNO);
    	retract(w);
end

rule "Futro"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Futro");
    then
    	insert(new Pytanie("Futro"));
        w.set("Czy twoj pokemon ma futro?", "Futro", FormatOdp.YESNO);
    	retract(w);
end

rule "Wasy"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Wasy");
    then
    	insert(new Pytanie("Wasy"));
        w.set("Czy twoj pokemon ma wasy?", "Wasy", FormatOdp.YESNO);
    	retract(w);
end

rule "Jezyk"
    when
    	w : Wyswietlanie();
    	not Pytanie(tekst == "Jezyk");
    then
    	insert(new Pytanie("Jezyk"));
        w.set("Czy twoj pokemon ma wytkniety jezyk?", "Jezyk", FormatOdp.YESNO);
    	retract(w);
end

// ************************************
//			Pasuj¹ce Rasy i Klasy 
//				20 klas
// ************************************

//Ludzie
rule "Mag"
    when
    	w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Mag", true);        
    	retract(w);
end

rule "Wojownik"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Wojownik", true);        
    	retract(w);
end

rule "Paladyn"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
	then
	w.set("Paladyn", true);        
    	retract(w)
end


rule "£otrzyk"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("£otrzyk", true);        
    	retract(w);
end

rule "Strzelec"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Strzelec", true);        
    	retract(w);
end

rule "In¿yniert"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("In¿ynier", true);        
    	retract(w);
end

//Orki
rule "Barbarzynca"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Barbarzynca", true);        
    	retract(w);
end


rule "Szaman"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Szaman", true);        
    	retract(w);
end

rule "Lowca"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Lowca", true);        
    	retract(w);
end

rule "Jezdziec Wilkow"
	when
		w : Wyswietlanie();
    	//do uzupe³nienia cechy
    then
    	w.set("Nidoking", true);        
    	retract(w);
end

rule "Olbrzym"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Olbrzym", true);        
    	retract(w);
end

rule "Gremlin"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Gremlin", true);        
    	retract(w);
end

//Elfy
rule "Uzdrowicie;"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Uzdrowiciel", true);        
    	retract(w);
end

rule "Bard"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Bard", true);        
    	retract(w);
end

rule "£ucznik"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("£ucznik", true);        
    	retract(w);
end

rule "Assasyn"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Assasyn", true);        
    	retract(w);
end

rule "Druid"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Druid", true);        
    	retract(w);
end

rule "Mêdrzec"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Mêdrzec", true);        
    	retract(w);
end

//klasy bez rasy
rule "Dragonborn"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Dragonborn", true);        
    	retract(w);
end

rule "Wiedzmin"
	when
		w : Wyswietlanie();
		//do uzupe³nienia cechy
    then
    	w.set("Wiedzmin", true);        
    	retract(w);
end



/* Przyk³ad rule z odpowiedzi¹
rule "Arcanine"
	when
		w : Wyswietlanie();
		Cecha(tresc == "Nogi4");
		(or
			Cecha(tresc == "NogiKoloruPomaranczowego");
			Cecha(tresc == "NogiKoloruCzarnego");
		)
		Cecha(tresc == "Oczy2");
		Cecha(tresc == "Wzor");
		Cecha(tresc == "UszyKoloruPomaranczowego");
		Cecha(tresc == "OgonKoloruKremowego");
		Cecha(tresc == "Futro");
    then
    	w.set("Arcanine", true);        
    	retract(w);
end
*/