package com.sample

import com.sample.DroolsTest.*;
import java.util.List;
import java.util.ArrayList;
  
query "Display"
    w : Display();
end

// ************************************
//			PYTANIA
//		10 pytañ g³ownych, 11 szczegó³oweych i 6 ogolnych
// ************************************


// pytania wynikaj¹ce z innych maj¹ wy¿szy prioritet, aby zaraz potem siê zada³y
rule "Wielkosc" salience 1
    when
    	w : Display();
    	not Question (tekst == "Wielkosc");
    then
    	insert(new Question ("Wielkosc"));
        w.setResult ("Czy wielkoœæ twojej postaci ma znaczenie?", "Wielkosc", QuestionType.YESNO);
    	retract(w);
end

rule "WielkoscDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Wielkosc");
    	not Question (tekst == "WielkoscDwa");
    then
    	insert(new Question ("WielkoscDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Ma³y");
    		warianty.add("Du¿y");
    		warianty.add("Wielki");
        w.setResult ("Jak du¿y chcia³byœ byæ?", "", QuestionType.RADIOBUTTON, warianty);
    	retract(w);
end


rule "Wiek" salience 1
    when
    	w : Display();
    	not Question (tekst == "Wiek");
    then
    	insert(new Question ("Wiek"));
        w.setResult ("Czy wiek towjej postaci ma znaczenie?", "Wiek", QuestionType.YESNO);
    	retract(w);
end


rule "WiekDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Wielkosc");
    	not Question (tekst == "WielkoscDwa");
    then
    	insert(new Question ("WielkoscDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("M³oda");
    		warianty.add("W œrednim wieku");
    		warianty.add("Stara");
        w.setResult ("Jaki wiek twojej postac preferujesz?", "", QuestionType.RADIOBUTTON, warianty);
    	retract(w);
end

rule "Walczy" salience 1
    when
    	w : Display();
    	not Question (tekst == "Walczy");
    then
    	insert(new Question ("Walczy"));
        w.setResult ("Czy chcesz walczyæ?", "Walczy", QuestionType.YESNO);
    	retract(w);
end

rule "Bron" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Walczy");
    	not Question (tekst == "Bron");
    then
    	insert(new Question ("Bron"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Miecz");
    		warianty.add("Kostur");
    		warianty.add("Topór");
    		warianty.add("£uk");
    		warianty.add("Kusza");
    		warianty.add("Pistolet");
    		warianty.add("Sztylety");
    		warianty.add("Maczuga");
        w.setResult ("Jakie bronie lubisz?", "",  QuestionType.WIELOKROTYN, warianty);
    	retract(w);
end

rule "Wszechstronny" salience 1
    when
    	w : Display();
    	not Question (tekst == "Wszechstronny");
    then
    	insert(new Question ("Wszechstronny"));
        w.setResult ("Czy chcesz byæ wszechstronny(ale nie wybitny w konkretnej dziedzinie)?", "Wszechstronny", QuestionType.YESNO);
    	retract(w);
end

rule "WszechstronnyDwa" salience 2
    when
    	w : Display();
    	Attribute ( tresc == "Wszechstronny");
    	not Question (tekst == "WszechstronnyDwa");
    then
    	insert(new Question ("WszechstronnyDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Inteligencja");
    		warianty.add("Spryt");
    		warianty.add("Si³a");
        w.setResult ("Jaka Attribute  jest dla Ciebie najwa¿niejsza?", "", QuestionType.YESNO);
    	retract(w);
end



rule "Zaklecia" salience 1
    when
    	w : Display();
    	not Question (tekst == "Zaklecia");
    then
    	insert(new Question ("Zaklecia"));
        w.setResult ("Czy chcesz uzywac zaklec?", "Zaklecia", QuestionType.YESNO);
    	retract(w);
end


rule "ZakleciaDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Zaklecia");
    	not Question (tekst == "ZakleciaDwa");
    then
    	insert(new Question ("ZakleciaDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Lecznicze");
    		warianty.add("Wojenne");
    		warianty.add("Kl¹twy");
    		warianty.add("Wspieraj¹ce");
        w.setResult ("Jakie zaklêcia wolisz?", "Zaklecia", QuestionType.RADIOBUTTON, warianty);
    	retract(w);
end


rule "Kolor" salience 1
    when
    	w : Display();
    	not Question (tekst == "Kolor");
    then
    	insert(new Question ("Kolor"));
        w.setResult ("Czy masz ulubiony kolor?", "Kolor", QuestionType.YESNO);
    	retract(w);
end

rule "KolorDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Kolor");
    	not Question (tekst == "KolorDwa");
    then
    	insert(new Question ("KolorDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Ró¿owy");
    		warianty.add("Zielony");
    		warianty.add("Czarny");
    		warianty.add("Bia³y");
    		warianty.add("Czerwony");
    		warianty.add("Inny");
        w.setResult ("Jaki jest twój ulubiony kolor?", "Kolor", QuestionType.RADIOBUTTON, warianty);
        retract(w);
end

rule "Siedziba" salience 1
    when
    	w : Display();
    	not Question (tekst == "Siedziba");
    then
    	insert(new Question ("Siedziba"));
        w.setResult ("Czy chcesz miec sta³¹ siedzibê?", "Siedziba", QuestionType.YESNO);
    	retract(w);
end

rule "SiedzibaDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Siedziba");
    	not Question (tekst == "SiedzibaDwa");
    then
    	insert(new Question ("SiedzibaDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("W chacie");
    		warianty.add("W lesie");
    		warianty.add("W grocie");
    		warianty.add("W wie¿y");
        w.setResult ("Gdzie chcia³byœ zamieszkaæ?", "", QuestionType.RADIOBUTTON, warianty);
    	retract(w);
end

rule "Pancerz" salience 1
    when
    	w : Display();
    	not Question (tekst == "Pancerz");
    then
    	insert(new Question ("Pancerz"));
        w.setResult ("Czy chcesz byc opancerzony?", "Pancerz", QuestionType.YESNO);
    	retract(w);
end

rule "PancerzDwa" salience 2
    when
    	w : Display();
    	Attribute (tresc == "Pancerz");
    	not Question (tekst == "PancerzDwa");
    then
    	insert(new Question ("PancerzDwa"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Ciê¿ka zbroja");
    		warianty.add("He³m z rogami");
    		warianty.add("Tarcza");
    		warianty.add("Lekka zbroja");
    		warianty.add("Skórzana zbroja");
    		
        w.setResult ("Jaki pancerz?", "", QuestionType.WIELOKROTYN, warianty);
    	retract(w);
end

rule "Wegetarianin" salience 1
    when
    	w : Display();
    	not Question (tekst == "Wegetarianin");
    then
    	insert(new Question ("Wegetarianin"));
        w.setResult ("Czy jesteœ wegetarianinem?", "Wegetarianin", QuestionType.YESNO);
    	retract(w);
end

rule "Mieso" salience 2
    when
    	w : Display();
    	not Attribute  (tresc == "Wegetarianin");
    	Question (tekst == "Wegetarianin");
    	not Question (tekst == "Mieso");
    then
    	insert(new Question ("Mieso"));
        w.setResult ("Czy zjad³byœ miêso cz³onka w³asnej rasy?", "Mieso", QuestionType.YESNO);
    	retract(w);
end

rule "Zwierze" salience 1
    when
    	w : Display();
    	not Question (tekst == "Zwierze");
    then
    	insert(new Question ("Zwierze"));
        w.setResult ("Czy lubisz zwierzêta?", "Zwierze", QuestionType.YESNO);
    	retract(w);
end
 
rule "ZwierzDwa" salience 2
    when
    	w : Display();
    	Attribute  (tresc == "Zwierze");
    	not Question (tekst == "ZwierzeDwa");
    then
    	insert(new Question ("ZwierzeDwa"));
        w.setResult ("Czy chcia³byœ mieæ zwierzê?", "MaZwierze", QuestionType.YESNO);
    	retract(w);
end


rule "ZwierzeTrzy" salience 3
    when
    	w : Display();
    	Attribute ( tresc == "MaZwierze");
    	not Question (tekst == "ZwierzeTrzy");
    then
    	insert(new Question ("ZwierzeTrzy"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Konia");
    		warianty.add("Wilka");
    		warianty.add("Kruka");
    		warianty.add("Sowê");
        w.setResult ("Jakie zwierzê chcia³byœ mieæ?", "",  QuestionType.RADIOBUTTON, warianty);
    	retract(w);
end


rule "Uczciwy" 
    when
    	w : Display();
    	not Question (tekst == "Uczciwy");
    then
    	insert(new Question ("Uczciwy"));
        w.setResult ("Czy znasz pojêcie uczciwoœci?", "Uczciwy", QuestionType.YESNO);
    	retract(w);
end

rule "Piekny" 
    when
    	w : Display();
    	not Question (tekst == "Piekny");
    then
    	insert(new Question ("Piekny"));
        w.setResult ("Czy chcesz byæ piêkny?", "Piekny", QuestionType.YESNO);
    	retract(w);
end

rule "Hobby" 
    when
    	w : Display();
    	not Question (tekst == "Hobby");
    then
    	insert(new Question ("Hobby"));
    	List<String> warianty = new ArrayList<String>();
    		warianty.add("Ksiêgi");
    		warianty.add("Zabawa");
    		warianty.add("Mechanizmy");
    		warianty.add("Zielarstwo");
    		warianty.add("Numizmatyka");
    		warianty.add("Zbieranie kamieni");
    		warianty.add("Zbieranie wszystkiego");
        w.setResult ("Jakie jest Twoje hobby?", "",  QuestionType.WIELOKROTYN, warianty);
    	retract(w);
end

rule "Dobry" 
    when
    	w : Display();
    	not Question (tekst == "Dobro");
    then
    	insert(new Question ("Dobro"));
        w.setResult ("Czy chcesz czyniæ dobro?", "Dobry", QuestionType.YESNO);
    	retract(w);
end

rule "Szybki" 
    when
    	w : Display();
    	not Question (tekst == "Szybki");
    then
    	insert(new Question ("Szybki"));
        w.setResult ("Czy lubisz prêdkoœæ?", "Szybki", QuestionType.YESNO);
    	retract(w);
end

rule "Wynalazki" 
    when
    	w : Display();
    	not Question (tekst == "Wynalazki");
    then
    	insert(new Question ("Wynalazki"));
        w.setResult ("Czy lubisz gad¿ety/wynalazki?", "Wynalazki", QuestionType.YESNO);
    	retract(w);
end
// ************************************
//			 Rasy i Klasy 
//				22 klasy
// ************************************

// ******************Ludzie*********************
rule "Mag" salience 3
    when
    	w : Display();
    	Attribute ( tresc == "Stary");
		Attribute ( tresc == "Kostur");
		Attribute ( tresc == "Ineligencja");
		Attribute ( tresc == "W Wie¿y");
		Attribute ( tresc == "Lekka zbroja");
		Attribute ( tresc == "Sowê");
		Attribute ( tresc == "Ksiêgi");
    then
    	w.setResult ("Mag", true);        
    	retract(w);
end

rule "Wojownik" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Du¿y");
		Attribute ( tresc == "M³oda");
		(or
			Attribute ( tresc == "Miecz");
			Attribute ( tresc == "Topór");
			Attribute ( tresc == "£uk");
			)
		Attribute ( tresc == "Si³a");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Ciê¿ka zbroja");
    then
    	w.setResult ("Wojownik", true);        
    	retract(w);
end

rule "Paladyn" salience 3
	when
		w : Display();
		Attribute ( tresc == "Du¿y");
		Attribute ( tresc == "MaZwierze");
		Attribute ( tresc == "M³oda");
		Attribute ( tresc == "Miecz");
		Attribute ( tresc == "ZakleciaWspieraj¹ce");
		Attribute ( tresc == "W chacie");
		(or
			Attribute ( tresc == "Ciê¿ka Zbroja");
			Attribute ( tresc == "Tarcza");
			)
		Attribute ( tresc == "Konia");
		Attribute ( tresc == "Uczciwy");
		Attribute ( tresc == "Dobry");
		Attribute ( tresc == "Szybki");
	then
	w.setResult ("Paladyn", true);        
    	retract(w)
end

rule "£otrzyk" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Ma³y");
		not Attribute ( tresc == "Uczciwy");
		Attribute ( tresc == "KolorCzarny");
		Attribute ( tresc == "M³oda");
		Attribute ( tresc == "Sztylety");
		Attribute ( tresc == "Spryt");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Lekka zbroja");
		Attribute ( tresc == "Numizmatyka");
		Attribute ( tresc == "Szybki");
    then
    	w.setResult ("£otrzyk", true);        
    	retract(w);
end

rule "Strzelec" salience 3
	when
		w : Display();
    	Attribute ( tresc == "M³oda");
		Attribute ( tresc == "Pistolet");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Lekka zbroja");
		Attribute ( tresc == "Skórzana zbroja");
    then
    	w.setResult ("Strzelec", true);        
    	retract(w);
end

rule "In¿yniert" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Ma³y");
		not Attribute ( tresc == "Walczy");
		Attribute ( tresc == "W œrednim wieku");
		Attribute ( tresc == "Inteligencja");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Mechanizmy");
		Attribute ( tresc == "Dobry");
		Attribute ( tresc == "Wynalazki");
    then
    	w.setResult ("In¿ynier", true);        
    	retract(w);
end



// *******************Orki*********************
rule "Barbarzynca" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Du¿y");
		(or
			Attribute ( tresc == "Miecz");
			Attribute ( tresc == "Topór");
			Attribute ( tresc == "Maczuga");
		)
		Attribute ( tresc == "Si³a");
		Attribute ( tresc == "W grocie");
		Attribute ( tresc == "Skórzana zbroja");
		not Attribute ( tresc == "Uczciwy");
		Attribute ( tresc == "Numizmatyka");
    then
    	w.setResult ("Barbarzynca", true);        
    	retract(w);
end


rule "Szaman" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Inteligencja");
		Attribute ( tresc == "ZakleciaWojenne");
		Attribute ( tresc == "ZakleciaKl¹twy");
		Attribute ( tresc == "W wie¿y");
		Attribute ( tresc == "Lekka zbroja");
		Attribute ( tresc == "Kruka");
		Attribute ( tresc == "Ksiêgi");
    then
    	w.setResult ("Szaman", true);        
    	retract(w);
end

rule "£owca" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Du¿y");
		(or
			Attribute ( tresc == "£uk");
			Attribute ( tresc == "Kusza");
		)
		Attribute ( tresc == "W grocie");
		Attribute ( tresc == "Lekka zbroja");
		Attribute ( tresc == "Wilka");
    then
    	w.setResult ("£owca", true);        
    	retract(w);
end

rule "Jezdziec Wilkow" salience 3
	when
		w : Display();
    	Attribute ( tresc == "Du¿y");
    	Attribute ( tresc == "MaZwierze");
		(or
			Attribute ( tresc == "Miecz");
			Attribute ( tresc == "Topór");
		)
		(or
			Attribute ( tresc == "Spryt");
			Attribute ( tresc == "Si³a");
		)
		Attribute ( tresc == "W grocie");
		Attribute ( tresc == "Skórzana zbroja");
    	Attribute ( tresc == "Wilka");
    	Attribute ( tresc == "Szybki");
    then
    	w.setResult ("Jezdziec Wilkow", true);        
    	retract(w);
end

rule "Olbrzym" salience 3
	when
		w : Display();
		Attribute ( tresc == "Wielki");
		Attribute ( tresc == "Maczuga");
    	Attribute ( tresc == "Si³a");
    	Attribute ( tresc == "W grocie");
    	Attribute ( tresc == "Zieranie kamieni");
    then
    	w.setResult ("Olbrzym", true);        
    	retract(w);
end

rule "Gremlin" salience 3
	when
		w : Display();
		Attribute ( tresc == "Ma³y");
		not Attribute ( tresc == "Uczciwy");
    	(or
    		Attribute ( tresc == "£uk");
    		Attribute ( tresc == "Sztylety");
    	)
    	Attribute ( tresc == "Spryt");
    	Attribute ( tresc == "W grocie");
    	Attribute ( tresc == "Lekka zbroja");
    	Attribute ( tresc == "Zbieranie wszystkiego");
    then
    	w.setResult ("Gremlin", true);        
    	retract(w);
end

//Elfy
rule "Uzdrowicie;" salience 3
	when
		w : Display();
		Attribute ( tresc == "Piekny");
    	not Attribute ( tresc == "Walczy");
    	Attribute ( tresc == "Inteligencja");
    	(or
    		Attribute ( tresc == "ZakleciaLecznicze");
    		Attribute ( tresc == "ZakleciaWspierajace");
    		)
    	Attribute ( tresc == "W lesie");
    	Attribute ( tresc == "Sowê");
    	Attribute ( tresc == "Uczciwy");
    	Attribute ( tresc == "Ksiêgi");
    	Attribute ( tresc == "Zielarstwo");
    	Attribute ( tresc == "Dobry");
    then
    	w.setResult ("Uzdrowiciel", true);        
    	retract(w);
end

rule "Bard" salience 3
	when
		w : Display();
		Attribute ( tresc == "Piekny");
    	not Attribute ( tresc == "Walczy");
    	Attribute ( tresc == "KolorRó¿owy");
    	Attribute ( tresc == "Konia");
    	Attribute ( tresc == "Zabawa");
    then
    	w.setResult ("Bard", true);        
    	retract(w);
end

rule "£ucznik" salience 3
	when
		w : Display();
		Attribute ( tresc == "Piekny");
    	Attribute ( tresc == "£uk");
    	Attribute ( tresc == "W lesie");
    	Attribute ( tresc == "Lekka zbroja");
    	(or
    		Attribute ( tresc == "Konia");
    		Attribute ( tresc == "Wilka");
    	)
    	Attribute ( tresc == "Uczciwy");
    	Attribute ( tresc == "Szybki");
    then
    	w.setResult ("£ucznik", true);        
    	retract(w);
end

rule "Assasyn" salience 3
	when
		w : Display();
		Attribute ( tresc == "Piekny");
    	Attribute ( tresc == "KolorCzarny");
    	(or
    		Attribute ( tresc == "Miecz");
    		Attribute ( tresc == "Kusza");
    		Attribute ( tresc == "£uk");
    		Attribute ( tresc == "Sztylety");
    	)
    	Attribute ( tresc == "Spryt");
    	Attribute ( tresc == "W lesie");
    	Attribute ( tresc == "Lekka zbroja");
    	Attribute ( tresc == "Szybki");
    then
    	w.setResult ("Assasyn", true);        
    	retract(w);
end

rule "Druid" salience 3
	when
		w : Display();
		Attribute ( tresc == "MaZwierze");
    	not Attribute ( tresc == "Walczy");
    	Attribute ( tresc == "KolorZielony");
    	Attribute ( tresc == "W lesie");
    	(or
    		Attribute ( tresc == "Wilka");
    		Attribute ( tresc == "Kruka");
    	)
    	Attribute ( tresc == "Uczciwy");
    	Attribute ( tresc == "Dobry");
    then
    	w.setResult ("Druid", true);        
    	retract(w);
end

rule "Mêdrzec" salience 3
	when
		w : Display();
		Attribute ( tresc == "Stary");
    	not Attribute ( tresc == "Walczy");
    	Attribute ( tresc == "Inteligencja");
    	(or
    		Attribute ( tresc == "ZakleciaLecznicze");
    		Attribute ( tresc == "ZakleciaWojenne");
    	)
    	Attribute ( tresc == "W wie¿y");
    	Attribute ( tresc == "Sowê");
    	Attribute ( tresc == "Uczciwy");
    	Attribute ( tresc == "Ksiêgi");
    	Attribute ( tresc == "Zielarstwo");
    then
    	w.setResult ("Mêdrzec", true);        
    	retract(w);
end

// *************klasy bez rasy**********************
rule "Dragonborn" salience 3
	when
		w : Display();
		Attribute ( tresc == "MaZwierze");
		Attribute ( tresc == "Wszechstronny");
		Attribute ( tresc == "KolorCzerwony");
		(or
		Attribute ( tresc == "Miecz");
		Attribute ( tresc == "Topór");
		Attribute ( tresc == "Kusza");
		Attribute ( tresc == "£uk");
		)
		Attribute ( tresc == "Si³a");
		Attribute ( tresc == "ZakleciaWojenne");
		Attribute ( tresc == "Ciê¿ka zbrojê");
		Attribute ( tresc == "He³m z rogami");
		Attribute ( tresc == "Konia");
		Attribute ( tresc == "bieranie wszystkiego");
		Attribute ( tresc == "Szybki");
		
    then
    	w.setResult ("Dragonborn", true);        
    	retract(w);
end
 
rule "Z³odziej" salience 3
	when
		w : Display();
		not Attribute ( tresc == "Walczy");
		Attribute ( tresc == "Szybki");
		not Attribute ( tresc == "Uczciwy");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Zbieranie wszystkiego");
		Attribute ( tresc == "Numizmatyka ");
		Attribute ( tresc == "Wynalazki");
	then
		w.setResult ("WiedŸmin",true);	
		retract(w);
end

rule "Pijak" salience 3
	when
		w : Display();
		Attribute ( tresc == "Walczy");
		Attribute ( tresc == "Zielarstwo");
		Attribute ( tresc == "W chacie");
		Attribute ( tresc == "Stary ");
		Attribute ( tresc == "Zbieranie wszystkiego");
		not Attribute ( tresc == "Szybki");
	then
		w.setResult ("Pijak",true);	
		retract(w);
end

rule "WiedŸmin" salience 3
	when
		w : Display();
		Attribute ( tresc == "MaZwierze");
		Attribute ( tresc == "KolorBia³y");
		(or
			Attribute ( tresc == "Miecz");
			Attribute ( tresc == "Kusza");
		)
		Attribute ( tresc == "ZakleciaWojenne");
		Attribute ( tresc == "Skórzana zbroja");
		Attribute ( tresc == "Konia");
		Attribute ( tresc == "Zielarstwo");
		Attribute ( tresc == "Szybki");
    then
    	w.setResult ("WiedŸmin", true);        
    	retract(w);
end
